version: "3.9"
services:
  vue-frontend:
    build:
      context: ./SFaaS_Front
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./SFaaS_Front:/app
    command: npm run serve
    depends_on:
      - python-backend

  python-backend:
    build:
      context: ./FastApi
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
